apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  namespace: default
spec:
  rules:
  - host: www.evankao.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 31374
